--TABLE CUSTOMER +
CREATE TABLE CUSTOMER(
    ID_CUSTOMER INT NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    GENDER CHAR(1),
    DATE_BIRTH DATE,
    TELEPHONE VARCHAR(20),
    AMOUNT_BOOKINGS INT
);

--TABLE TRAVEL AGENCY +
CREATE TABLE TRAVEL_AGENCY(
    ID_AGENCY INT NOT NULL PRIMARY KEY ,
    TELEPHONE VARCHAR(10)
);

--TABLE ADDRESS OF AGENCY + 
CREATE TABLE ADDRESS_AGENCY(
    ID_ADDRESS INT NOT NULL PRIMARY KEY ,
    CITY VARCHAR(20),
    STREET VARCHAR(50),
    ID_AGENCY INT NOT NULL,

    FOREIGN KEY (ID_AGENCY) REFERENCES TRAVEL_AGENCY (ID_AGENCY)
);

--TABLE VISA +
CREATE TABLE VISA(
    ID_VISA INT NOT NULL PRIMARY KEY,
    NUMBER_VISA INT not null,
    VISA_TYPE VARCHAR(20) NULL,
    DATE_OF_ISSUE DATE NULL,
    DATE_EXPIRE DATE NULL,
    COUNTRY VARCHAR(50) Null
);

--TABLE PASSPORT +
CREATE TABLE PASSPORT(
    ID_PASSPORT INT NOT NULL PRIMARY KEY,
    NUMER VARCHAR(10) NULL,
    PESELE INT NOT NULL,
    DATE_OF_ISSUE DATE NULL,
    DATE_EXPIRE DATE NULL,
    ID_CUSTOMER INT NOT NULL,
    ID_VISA INT NULL,

    FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER (ID_CUSTOMER),
    FOREIGN KEY (ID_VISA) REFERENCES VISA (ID_VISA)
);

--TABLE COUNTRY +
CREATE TABLE COUNTRY(
    ID_COUNTRY INT NOT NULL PRIMARY KEY ,
    NAME VARCHAR(20) NOT NULL
);

--TABLE HOTEL +
CREATE TABLE HOTEL(
    ID_HOTEL INT NOT NULL PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    STARS_NUMBER INT NOT NULL
);

--TABLE TRANSPORT +
CREATE TABLE TRANSPORT(
    ID_TRANSPORT INT NOT NULL PRIMARY KEY ,
    ID_BUS INT  NULL,
    ID_AIRPLANE INT  NULL,
    ID_TRAIN INT NULL,

    FOREIGN KEY (ID_AIRPLANE) REFERENCES AIRPLANE (ID_AIRPLANE),
    FOREIGN KEY (ID_TRAIN) REFERENCES TRAIN (ID_TRAIN),
    FOREIGN KEY (ID_BUS) REFERENCES BUS (ID_BUS)
);

--TABLE BUS +
CREATE TABLE BUS(
    ID_BUS INT NOT NULL PRIMARY KEY ,
    TIME_DEPARTURE TIMESTAMP NOT NULL,
    SEATS_NUMBER INT NOT NULL
);

--TABLE AIRPLANE +
CREATE TABLE AIRPLANE(
    ID_AIRPLANE INT NOT NULL PRIMARY KEY,
    TIME_DEPARTURE TIMESTAMP NOT NULL,
    FLIGHT_NUMBER VARCHAR(10) NOT NULL
);

--TABLE TRAIN +
CREATE TABLE TRAIN(
    ID_TRAIN INT NOT NULL PRIMARY KEY ,
    TIME_DEPARTURE TIMESTAMP NOT NULL,
    TICKET_NUMBER VARCHAR(10) NOT NULL
);

--TABLE RESTAURANT +
CREATE TABLE RESTAURANT(
    ID_RESTAURANT INT NOT NULL PRIMARY KEY ,
    NAME VARCHAR(20) NOT NULL,
    DATE_RESERVATION DATE NOT NULL
);

--TABLE PAYMENTS +
CREATE TABLE PAYMENT(
    ID_PAYMENT INT NOT NULL PRIMARY KEY ,
    AMOUNT INT NOT NULL,
    DATE_PAYMENT DATE NULL
);

--TABLE TRIP +
CREATE TABLE TRIP(
    ID_TRIP INT NOT NULL PRIMARY KEY ,
    DATE_OF_ISSUE DATE,
    DATE_EXPIRE DATE NULL,
    ID_PAYMENT INT NOT NULL,
    ID_COUNTRY INT NOT NULL,
    ID_HOTEL INT NOT NULL,
    ID_RESTAURANT INT NOT NULL,
    ID_TRANSPORT INT NOT NULL,

    FOREIGN KEY (ID_PAYMENT) REFERENCES PAYMENT (ID_PAYMENT),
    FOREIGN KEY (ID_COUNTRY) REFERENCES COUNTRY (ID_COUNTRY),
    FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL (ID_HOTEL),
    FOREIGN KEY (ID_RESTAURANT) REFERENCES RESTAURANT (ID_RESTAURANT),
    FOREIGN KEY (ID_TRANSPORT) REFERENCES TRANSPORT (ID_TRANSPORT)
);

--TABLE BOOKING +
CREATE TABLE BOOKING(
    ID_BOOKING INT NOT NULL PRIMARY KEY ,
    DATE_SELLING DATE,
    ID_CUSTOMER INT NOT NULL,
    ID_TRIP INT NOT NULL,
    ID_AGENCY INT NOT NULL,

    FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER (ID_CUSTOMER),
    FOREIGN KEY (ID_TRIP) REFERENCES TRIP (ID_TRIP),
    FOREIGN KEY (ID_AGENCY) REFERENCES TRAVEL_AGENCY (ID_AGENCY)
);


