--TABLE CUSTOMER
CREATE TABLE CUSTOMER(
    ID_CUSTOMER INT NOT NULL,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    GENDER CHAR(1),
    DATE_BIRTH DATE,
    TELEPHONE VARCHAR(20),
    AMOUNT_BOOKINGS INT,

    CONSTRAINT CUSTOMER_PK PRIMARY KEY (ID_CUSTOMER)
);

--TABLE TRAVEL AGENCY
CREATE TABLE TRAVEL_AGENCY(
    ID_AGENCY INT NOT NULL,
    TELEPHONE VARCHAR(10),

    CONSTRAINT AGENCY_PK PRIMARY KEY (ID_AGENCY)
);

--TABLE ADDRESS OF AGENCY
CREATE TABLE ADDRESS_AGENCY(
    ID_ADDRESS INT NOT NULL,
    CITY VARCHAR(20),
    STREET VARCHAR(50),
    ID_AGENCY INT not null,

    CONSTRAINT ADDRESS_AGENCY_PK PRIMARY KEY (ID_ADDRESS),

    CONSTRAINT TRAVEL_AGENCY_FK
        FOREIGN KEY (ID_AGENCY)
        REFERENCES TRAVEL_AGENCY(ID_AGENCY)
);

--TABLE PASSPORT
CREATE TABLE PASSPORT(
    ID_PASSPORT INT NOT NULL,
    NUMER VARCHAR(10) NULL,
    PESELE BIGINT NOT NULL,
    DATE_OF_ISSUE DATE NULL,
    DATE_EXPIRE DATE NULL,
    ID_CUSTOMER INT NOT NULL,
    ID_VISA INT NULL,

    CONSTRAINT PASSPORT_PK PRIMARY KEY (ID_PASSPORT),

    CONSTRAINT CUSTOMER_FK
        FOREIGN KEY (ID_CUSTOMER)
        REFERENCES CUSTOMER(ID_CUSTOMER),

    CONSTRAINT VISA_FK
        FOREIGN KEY (ID_VISA)
        REFERENCES VISA(ID_VISA)
);

--TABLE VISA
CREATE TABLE VISA(
    ID_VISA INT NOT NULL,
    NUMBER_VISA INT not null,
    VISA_TYPE VARCHAR(20) NULL,
    DATE_OF_ISSUE DATE NULL,
    DATE_EXPIRE DATE NULL,
    COUNTRY VARCHAR(50) NULL,

    CONSTRAINT VISA_PK PRIMARY KEY (ID_VISA)
);

--TABLE COUNTRY
CREATE TABLE COUNTRY(
    ID_COUNTRY INT NOT NULL,
    NAME VARCHAR(20) not null,

    CONSTRAINT COUNTRY_PK PRIMARY KEY (ID_COUNTRY)
);

--TABLE HOTEL
CREATE TABLE HOTEL(
    ID_HOTEL INT NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    STARS_NUMBER INT NOT NULL,

    CONSTRAINT HOTEL_PK PRIMARY KEY (ID_HOTEL)
);

--TABLE TRANSPORT
CREATE TABLE TRANSPORT(
    ID_TRANSPORT INT NOT NULL,
    ID_BUS INT NULL,
    ID_AIRPLANE INT NULL,
    ID_TRAIN INT NULL,

    CONSTRAINT TRANSPORT_PK PRIMARY KEY (ID_TRANSPORT),

    CONSTRAINT BUS_FK
        FOREIGN KEY (ID_BUS)
        REFERENCES BUS(ID_BUS),

    CONSTRAINT AIRPLANE_FK
        FOREIGN KEY (ID_AIRPLANE)
        REFERENCES AIRPLANE(ID_AIRPLANE),

    CONSTRAINT TRAIN_FK
        FOREIGN KEY (ID_TRAIN)
        REFERENCES TRAIN(ID_TRAIN)
);

--TABLE BUS
CREATE TABLE BUS(
    ID_BUS INT NOT NULL,
    TIME_DEPARTURE DATETIME NOT NULL,
    SEATS_NUMBER INT NOT NULL,

    CONSTRAINT BUS_PK PRIMARY KEY (ID_BUS)
);

--TABLE AIRPLANE
CREATE TABLE AIRPLANE(
    ID_AIRPLANE INT NOT NULL,
    TIME_DEPARTURE DATETIME NOT NULL,
    FLIGHT_NUMBER VARCHAR(10) NOT NULL,

    CONSTRAINT AIRPLANE_PK PRIMARY KEY (ID_AIRPLANE)
);

--TABLE TRAIN
CREATE TABLE TRAIN(
    ID_TRAIN INT NOT NULL,
    TIME_DEPARTURE DATETIME NOT NULL,
    TICKET_NUMBER VARCHAR(10) NOT NULL,

    CONSTRAINT TRAIN_PK PRIMARY KEY (ID_TRAIN)
);

--TABLE RESTAURANT
CREATE TABLE RESTAURANT(
    ID_RESTAURANT INT NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    DATE_RESERVATION DATE NOT NULL,

    CONSTRAINT RESTAURANT_PK PRIMARY KEY (ID_RESTAURANT)
);

--TABLE PAYMENTS
CREATE TABLE PAYMENT(
    ID_PAYMENT INT NOT NULL,
    AMOUNT INT NOT NULL,
    DATE_PAYMENT DATE null,

    CONSTRAINT PAYMENT_PK PRIMARY KEY (ID_PAYMENT)
);

--TABLE TRIP
CREATE TABLE TRIP(
    ID_TRIP INT NOT NULL,
    DATE_OF_ISSUE DATE,
    DATE_EXPIRE DATE NULL,
    ID_PAYMENT INT NOT NULL,
    ID_COUNTRY INT NOT NULL,
    ID_HOTEL INT NOT NULL,
    ID_RESTAURANT INT NOT NULL,
    ID_TRANSPORT INT NOT NULL,

    CONSTRAINT TRIP_PK PRIMARY KEY (ID_TRIP),

    CONSTRAINT PAYMENT_FK
        FOREIGN KEY (ID_PAYMENT)
        REFERENCES PAYMENT(ID_PAYMENT),

    CONSTRAINT COUNTRY_FK
        FOREIGN KEY (ID_COUNTRY)
        REFERENCES COUNTRY(ID_COUNTRY),

    CONSTRAINT HOTEL_FK
        FOREIGN KEY (ID_HOTEL)
        REFERENCES HOTEL(ID_HOTEL),

    CONSTRAINT RESTAURANTL_FK
        FOREIGN KEY (ID_RESTAURANT)
        REFERENCES RESTAURANT(ID_RESTAURANT),

    CONSTRAINT TRANSPORT_FK
        FOREIGN KEY (ID_TRANSPORT)
        REFERENCES TRANSPORT(ID_TRANSPORT)
);

--TABLE BOOKING
CREATE TABLE BOOKING(
    ID_BOOKING INT NOT NULL,
    DATE_SELLING DATE,
    ID_CUSTOMER INT NOT NULL,
    ID_TRIP INT NOT NULL,
    ID_AGENCY INT NOT NULL,

    CONSTRAINT BOOKING_PK PRIMARY KEY (ID_BOOKING),

    CONSTRAINT CUSTOMER_FK_BOOKING
        FOREIGN KEY (ID_CUSTOMER)
        REFERENCES CUSTOMER(ID_CUSTOMER),

    CONSTRAINT TRIP_FK_BOOKING
        FOREIGN KEY (ID_TRIP)
        REFERENCES TRIP(ID_TRIP),

    CONSTRAINT TRAVEL_AGENCY_FK_BOOKING
        FOREIGN KEY (ID_AGENCY)
        REFERENCES TRAVEL_AGENCY(ID_AGENCY)
);